import { StateLawData } from '@/types/stateLaw'

export const californiaData: StateLawData = {
  code: 'CA',
  name: 'California',

  residency: {
    state_months: 6,
    county_months: 3,
    statute: 'Family Code § 2320',
    proof_documents: [
      "California driver's license or ID card",
      'Utility bill (gas, electric, water) showing CA address',
      'Lease or mortgage agreement',
      'Voter registration card',
      'Vehicle registration',
    ],
    alternative_proof: [
      'Bank statements with CA address',
      'Employment records with CA address',
      'School enrollment records',
    ],
    minimum_proof: 'One government-issued ID document + one address document, OR two address documents',
    military_exception: true,
    student_exception: 'Students may establish residency if they intend to remain in CA permanently',
  },

  waiting_period: {
    duration_days: 180,
    start_event: 'service_of_summons',
    earliest_judgment: '6 months + 1 day after service of summons and petition',
    statute: 'Family Code § 2339',
    exceptions: [],
    can_waive: false,
  },

  property_division: {
    system: 'community_property',
    default_split: '50/50',
    statute: 'Family Code § 2550',
    community_property_definition: 'All property acquired during marriage before date of separation is presumed community property',
    separate_property_definition: 'Property owned before marriage, acquired by gift or inheritance during marriage, or acquired after date of separation',
    date_of_separation_significant: true,
    commingling_rules: 'Separate property can become community property if commingled without adequate tracing. The burden of proof is on the party claiming separate property.',
  },

  grounds: {
    no_fault: true,
    grounds_options: [
      'Irreconcilable differences (no-fault)',
      'Incurable insanity (requires medical proof, rarely used)',
    ],
    statute: 'Family Code § 2310',
    legal_separation_available: true,
  },

  child_custody: {
    standard: 'best_interest_of_child',
    joint_custody_preference: true,
    factors: [
      'Health, safety, and welfare of the child',
      'History of abuse by either parent',
      'Nature and amount of contact with both parents',
      "Child's preference if of sufficient age and capacity (typically 14+)",
      'Habitual or continual illegal use of controlled substances or alcohol',
      "Each parent's ability to provide a stable environment",
      'Any other factor the court deems relevant',
    ],
    statute: 'Family Code § 3011, § 3040',
    geographic_restrictions: null,
  },

  child_support: {
    guideline_type: 'formula_based',
    statute: 'Family Code § 4055',
    factors: [
      'Net disposable income of each parent',
      "Percentage of time each parent has primary physical custody (timeshare %)",
      'Tax filing status and deductions',
      'Number of children from this relationship',
      'Health insurance costs for children',
      'Mandatory union dues and retirement contributions',
      'Childcare costs related to employment or training',
      'Hardship deductions (other children, extraordinary health expenses)',
    ],
    cap: null,
  },

  spousal_support: {
    temporary_support_formula: true,
    permanent_support_factors: 'Family Code § 4320',
    long_term_marriage_years: 10,
    modification_standard: 'Material change in circumstances',
    termination_events: [
      'Death of either party',
      'Remarriage of supported spouse',
      'Court order (typically half the length of marriage for marriages < 10 years)',
    ],
    duration_limits: 'Marriages < 10 years: support generally limited to half the length of the marriage. Marriages ≥ 10 years: no automatic termination date.',
  },

  forms: [
    {
      form_number: 'FL-100',
      form_name: 'Petition—Marriage/Domestic Partnership',
      form_type: 'petition',
      required_when: { always: true },
      order_in_process: 1,
      court_fee: 435.00,
      instructions_url: 'https://www.courts.ca.gov/documents/fl100.pdf',
    },
    {
      form_number: 'FL-110',
      form_name: 'Summons (Family Law)',
      form_type: 'summons',
      required_when: { always: true },
      order_in_process: 2,
      court_fee: 0,
      instructions_url: 'https://www.courts.ca.gov/documents/fl110.pdf',
    },
    {
      form_number: 'FL-115',
      form_name: 'Proof of Service of Summons',
      form_type: 'service',
      required_when: { always: true },
      order_in_process: 3,
      court_fee: 0,
      instructions_url: null,
    },
    {
      form_number: 'FL-120',
      form_name: 'Response—Marriage/Domestic Partnership',
      form_type: 'response',
      required_when: { always: true },
      order_in_process: 4,
      court_fee: 435.00,
      instructions_url: 'https://www.courts.ca.gov/documents/fl120.pdf',
    },
    {
      form_number: 'FL-140',
      form_name: 'Declaration of Disclosure',
      form_type: 'financial_disclosure',
      required_when: { always: true },
      order_in_process: 5,
      court_fee: 0,
      instructions_url: null,
    },
    {
      form_number: 'FL-142',
      form_name: 'Schedule of Assets and Debts',
      form_type: 'property',
      required_when: { has_property: true },
      order_in_process: 6,
      court_fee: 0,
      instructions_url: null,
    },
    {
      form_number: 'FL-150',
      form_name: 'Income and Expense Declaration',
      form_type: 'financial_disclosure',
      required_when: {
        or: [
          { spousal_support_requested: true },
          { has_children: true },
        ],
      },
      order_in_process: 7,
      court_fee: 0,
      instructions_url: 'https://www.courts.ca.gov/documents/fl150.pdf',
    },
    {
      form_number: 'FL-155',
      form_name: 'Financial Statement (Simplified)',
      form_type: 'financial_disclosure',
      required_when: { case_type: 'uncontested' },
      order_in_process: 7,
      court_fee: 0,
      instructions_url: null,
    },
    {
      form_number: 'FL-160',
      form_name: 'Property Declaration',
      form_type: 'property',
      required_when: { has_property: true },
      order_in_process: 8,
      court_fee: 0,
      instructions_url: null,
    },
    {
      form_number: 'FL-170',
      form_name: 'Declaration for Default or Uncontested Dissolution',
      form_type: 'declaration',
      required_when: { case_type: 'uncontested' },
      order_in_process: 9,
      court_fee: 0,
      instructions_url: null,
    },
    {
      form_number: 'FL-180',
      form_name: 'Judgment (Family Law)',
      form_type: 'judgment',
      required_when: { always: true },
      order_in_process: 10,
      court_fee: 0,
      instructions_url: null,
    },
    {
      form_number: 'FL-190',
      form_name: 'Notice of Entry of Judgment',
      form_type: 'judgment',
      required_when: { always: true },
      order_in_process: 11,
      court_fee: 0,
      instructions_url: null,
    },
    {
      form_number: 'FL-311',
      form_name: 'Child Custody and Visitation (Parenting Time) Attachment',
      form_type: 'custody',
      required_when: { has_children: true },
      order_in_process: 3,
      court_fee: 0,
      instructions_url: null,
    },
    {
      form_number: 'FL-341',
      form_name: 'Child Custody and Visitation Order Attachment',
      form_type: 'custody',
      required_when: { has_children: true },
      order_in_process: 10,
      court_fee: 0,
      instructions_url: null,
    },
    {
      form_number: 'FL-342',
      form_name: 'Child Support Information and Order Attachment',
      form_type: 'support',
      required_when: { has_children: true },
      order_in_process: 10,
      court_fee: 0,
      instructions_url: null,
    },
    {
      form_number: 'FL-343',
      form_name: 'Spousal, Partner, or Family Support Order Attachment',
      form_type: 'support',
      required_when: { spousal_support_requested: true },
      order_in_process: 10,
      court_fee: 0,
      instructions_url: null,
    },
  ],

  counties: [
    {
      county_name: 'Los Angeles',
      court_name: 'Superior Court of California, County of Los Angeles',
      court_address: '111 N Hill St, Los Angeles, CA 90012',
      court_phone: '(213) 830-0803',
      efiling_system: 'LASC eFiling',
      efiling_url: 'https://www.lacourt.org/efiling',
      filing_fees: { petition: 435, response: 435, motion: 60 },
    },
    {
      county_name: 'San Diego',
      court_name: 'Superior Court of California, County of San Diego',
      court_address: '1100 Union St, San Diego, CA 92101',
      court_phone: '(619) 844-2700',
      efiling_system: 'Odyssey',
      efiling_url: 'https://www.sdcourt.ca.gov/sdcourt/efiling',
      filing_fees: { petition: 435, response: 435, motion: 60 },
    },
    {
      county_name: 'Orange',
      court_name: 'Superior Court of California, County of Orange',
      court_address: '700 Civic Center Dr W, Santa Ana, CA 92701',
      court_phone: '(657) 622-5600',
      efiling_system: 'File & ServeXpress',
      efiling_url: 'https://www.occourts.org/online-services/efiling.html',
      filing_fees: { petition: 435, response: 435, motion: 60 },
    },
    {
      county_name: 'San Francisco',
      court_name: 'Superior Court of California, County of San Francisco',
      court_address: '400 McAllister St, San Francisco, CA 94102',
      court_phone: '(415) 551-4000',
      efiling_system: 'File & ServeXpress',
      efiling_url: 'https://www.sfsuperiorcourt.org/divisions/family',
      filing_fees: { petition: 435, response: 435, motion: 60 },
    },
  ],
}
