import { StateLawData } from '@/types/stateLaw'

export const floridaData: StateLawData = {
  code: 'FL',
  name: 'Florida',

  residency: {
    state_months: 6,
    county_months: 0,
    statute: 'Florida Statutes § 61.021',
    proof_documents: [
      'Florida driver\'s license or ID card',
      'Florida voter registration card',
      'Utility bill showing FL address',
      'Lease or mortgage agreement',
    ],
    alternative_proof: [
      'Affidavit from a corroborating witness who can testify to residency',
      'Military orders showing FL station',
      'Employment records',
    ],
    minimum_proof: 'One of: FL driver\'s license, FL voter registration, FL ID card, OR a corroborating witness affidavit',
    military_exception: true,
    student_exception: 'Military members stationed in FL may file in FL regardless of domicile',
  },

  waiting_period: {
    duration_days: 20,
    start_event: 'filing_of_petition',
    earliest_judgment: '20 days after petition is filed (21st day)',
    statute: 'Florida Statutes § 61.19',
    exceptions: [
      'Court may waive the 20-day waiting period for good cause',
    ],
    can_waive: true,
  },

  property_division: {
    system: 'equitable_distribution',
    default_split: 'Equitable (fair, not necessarily equal). Starting point is 50/50.',
    statute: 'Florida Statutes § 61.075',
    community_property_definition: 'Not applicable (equitable distribution state). "Marital property" includes assets and liabilities acquired during the marriage.',
    separate_property_definition: 'Non-marital property: assets acquired before marriage, by gift or inheritance during marriage, and income derived from non-marital assets (unless commingled).',
    date_of_separation_significant: false,
    commingling_rules: 'Non-marital assets can become marital if commingled with marital assets. Enhancement in value of non-marital assets during the marriage due to marital efforts may be subject to distribution.',
  },

  grounds: {
    no_fault: true,
    grounds_options: [
      'Marriage is irretrievably broken (no-fault)',
      'Mental incapacity of one party (adjudicated incapacitated for 3+ years)',
    ],
    statute: 'Florida Statutes § 61.052',
    legal_separation_available: false,
  },

  child_custody: {
    standard: 'best_interest_of_child',
    joint_custody_preference: true,
    factors: [
      'Demonstrated capacity and disposition of each parent to facilitate a close and continuing parent-child relationship',
      'Anticipated division of parental responsibilities after litigation',
      'Demonstrated capacity to determine, consider, and act upon the needs of the child',
      'Length of time the child has lived in a stable, satisfactory environment',
      'Geographic viability of the parenting plan',
      'Moral fitness of the parents',
      'Mental and physical health of the parents',
      'Home, school, and community record of the child',
      'Reasonable preference of the child (if court deems child of sufficient intelligence)',
      'Demonstrated knowledge, capacity, and disposition to be informed of circumstances of the child',
      'Evidence of domestic violence, sexual violence, child abuse, or child neglect',
      'Evidence that either parent has knowingly provided false information to the court',
      'Particular parenting task customarily performed by which parent',
      'Demonstrated capacity to maintain an environment free from substance abuse',
      'Developmental stages and needs of the child',
      'Any other factor relevant to the determination',
    ],
    statute: 'Florida Statutes § 61.13',
    geographic_restrictions: null,
  },

  child_support: {
    guideline_type: 'income_shares',
    statute: 'Florida Statutes § 61.30',
    factors: [
      'Combined net income of both parents',
      'Number of children',
      'Guideline amount from statutory table based on combined income',
      'Each parent\'s percentage share of combined income',
      'Health insurance costs for children',
      'Childcare/daycare costs',
      'Number of overnight stays with each parent',
      'Adjustments for children from other relationships',
    ],
    cap: null,
  },

  spousal_support: {
    temporary_support_formula: false,
    permanent_support_factors: 'Florida Statutes § 61.08',
    long_term_marriage_years: 17,
    modification_standard: 'Substantial change in circumstances not contemplated at time of final judgment',
    termination_events: [
      'Death of either party',
      'Remarriage of the supported spouse',
      'Supportive relationship (cohabitation) of the supported spouse',
    ],
    duration_limits: 'Short-term marriage (< 7 years): Bridge-the-gap only (max 2 years). Moderate-term (7-17 years): Rehabilitative or durational. Long-term (17+ years): Durational or permanent possible. 2023 reforms significantly limited permanent alimony.',
  },

  forms: [
    {
      form_number: '12.901(a)',
      form_name: 'Petition for Dissolution of Marriage with No Dependent or Minor Children',
      form_type: 'petition',
      required_when: { and: [{ always: true }] },
      order_in_process: 1,
      court_fee: 409.00,
      instructions_url: 'https://www.flcourts.gov/Resources-Services/Court-Improvement/Family-Courts/Family-Law-Self-Help-Information/Family-Law-Forms',
    },
    {
      form_number: '12.901(b)(1)',
      form_name: 'Petition for Dissolution of Marriage with Dependent or Minor Children',
      form_type: 'petition',
      required_when: { has_children: true },
      order_in_process: 1,
      court_fee: 409.00,
      instructions_url: null,
    },
    {
      form_number: '12.910(a)',
      form_name: 'Summons: Personal Service on an Individual',
      form_type: 'summons',
      required_when: { always: true },
      order_in_process: 2,
      court_fee: 0,
      instructions_url: null,
    },
    {
      form_number: '12.903(a)',
      form_name: 'Answer, Waiver, and Request for Copy of Final Judgment',
      form_type: 'response',
      required_when: { case_type: 'uncontested' },
      order_in_process: 3,
      court_fee: 0,
      instructions_url: null,
    },
    {
      form_number: '12.903(b)',
      form_name: 'Answer to Petition and Counterpetition',
      form_type: 'response',
      required_when: { case_type: 'contested' },
      order_in_process: 3,
      court_fee: 0,
      instructions_url: null,
    },
    {
      form_number: '12.902(b)',
      form_name: 'Family Law Financial Affidavit (Short Form)',
      form_type: 'financial_disclosure',
      required_when: { always: true },
      order_in_process: 4,
      court_fee: 0,
      instructions_url: null,
    },
    {
      form_number: '12.902(c)',
      form_name: 'Family Law Financial Affidavit (Long Form)',
      form_type: 'financial_disclosure',
      required_when: { has_property: true },
      order_in_process: 4,
      court_fee: 0,
      instructions_url: null,
    },
    {
      form_number: '12.902(e)',
      form_name: 'Marital Settlement Agreement for Dissolution with No Children',
      form_type: 'property',
      required_when: { case_type: 'uncontested' },
      order_in_process: 5,
      court_fee: 0,
      instructions_url: null,
    },
    {
      form_number: '12.902(f)(1)',
      form_name: 'Marital Settlement Agreement for Dissolution with Children',
      form_type: 'property',
      required_when: { and: [{ case_type: 'uncontested' }, { has_children: true }] },
      order_in_process: 5,
      court_fee: 0,
      instructions_url: null,
    },
    {
      form_number: '12.995(a)',
      form_name: 'Parenting Plan',
      form_type: 'custody',
      required_when: { has_children: true },
      order_in_process: 6,
      court_fee: 0,
      instructions_url: null,
    },
    {
      form_number: '12.947(a)',
      form_name: 'Child Support Guidelines Worksheet',
      form_type: 'support',
      required_when: { has_children: true },
      order_in_process: 7,
      court_fee: 0,
      instructions_url: null,
    },
    {
      form_number: '12.990(a)',
      form_name: 'Final Judgment of Dissolution of Marriage (Uncontested, No Children)',
      form_type: 'judgment',
      required_when: { case_type: 'uncontested' },
      order_in_process: 10,
      court_fee: 0,
      instructions_url: null,
    },
    {
      form_number: '12.990(b)(1)',
      form_name: 'Final Judgment of Dissolution with Children (Uncontested)',
      form_type: 'judgment',
      required_when: { and: [{ case_type: 'uncontested' }, { has_children: true }] },
      order_in_process: 10,
      court_fee: 0,
      instructions_url: null,
    },
    {
      form_number: '12.912(b)',
      form_name: 'Certificate of Compliance with Mandatory Disclosure',
      form_type: 'financial_disclosure',
      required_when: { always: true },
      order_in_process: 5,
      court_fee: 0,
      instructions_url: null,
    },
    {
      form_number: 'FL-PARENT-COURSE',
      form_name: 'Parenting Course Completion Certificate',
      form_type: 'other',
      required_when: { has_children: true },
      order_in_process: 8,
      court_fee: 0,
      instructions_url: null,
    },
  ],

  counties: [
    {
      county_name: 'Miami-Dade',
      court_name: 'Eleventh Judicial Circuit Court - Family Division',
      court_address: '73 W Flagler St, Miami, FL 33130',
      court_phone: '(305) 275-1155',
      efiling_system: 'Florida Courts E-Filing Portal',
      efiling_url: 'https://www.myflcourtaccess.com/',
      filing_fees: { petition: 409, response: 0, motion: 50 },
    },
    {
      county_name: 'Broward',
      court_name: 'Seventeenth Judicial Circuit Court - Family Division',
      court_address: '201 SE 6th St, Fort Lauderdale, FL 33301',
      court_phone: '(954) 831-6565',
      efiling_system: 'Florida Courts E-Filing Portal',
      efiling_url: 'https://www.myflcourtaccess.com/',
      filing_fees: { petition: 409, response: 0, motion: 50 },
    },
    {
      county_name: 'Hillsborough',
      court_name: 'Thirteenth Judicial Circuit Court - Family Law Division',
      court_address: '800 E Twiggs St, Tampa, FL 33602',
      court_phone: '(813) 276-8100',
      efiling_system: 'Florida Courts E-Filing Portal',
      efiling_url: 'https://www.myflcourtaccess.com/',
      filing_fees: { petition: 409, response: 0, motion: 50 },
    },
    {
      county_name: 'Orange',
      court_name: 'Ninth Judicial Circuit Court - Family Division',
      court_address: '425 N Orange Ave, Orlando, FL 32801',
      court_phone: '(407) 836-2000',
      efiling_system: 'Florida Courts E-Filing Portal',
      efiling_url: 'https://www.myflcourtaccess.com/',
      filing_fees: { petition: 409, response: 0, motion: 50 },
    },
  ],
}
