import { StateLawData } from '@/types/stateLaw'

export const texasData: StateLawData = {
  code: 'TX',
  name: 'Texas',

  residency: {
    state_months: 6,
    county_months: 3,
    statute: 'Texas Family Code § 6.301',
    proof_documents: [
      'Texas driver\'s license or ID card',
      'Utility bill showing TX address',
      'Lease or mortgage agreement',
      'Voter registration card',
      'Vehicle registration',
    ],
    alternative_proof: [
      'Affidavit of residency (sworn statement)',
      'Bank statements with TX address',
      'Employment records',
    ],
    minimum_proof: 'Affidavit of residency required, plus supporting documentation',
    military_exception: true,
    student_exception: 'Military members stationed in TX may file in TX regardless of domicile state',
  },

  waiting_period: {
    duration_days: 60,
    start_event: 'filing_of_petition',
    earliest_judgment: '60 days after petition is filed (61st day)',
    statute: 'Texas Family Code § 6.702',
    exceptions: [
      'Family violence protective order (waiver possible)',
    ],
    can_waive: true,
  },

  property_division: {
    system: 'community_property',
    default_split: '50/50 (but court may order "just and right" division)',
    statute: 'Texas Family Code § 7.001',
    community_property_definition: 'Property acquired by either spouse during marriage, other than separate property',
    separate_property_definition: 'Property owned before marriage, acquired during marriage by gift, devise, or descent, or recovery for personal injuries (except lost earning capacity)',
    date_of_separation_significant: false,
    commingling_rules: 'Community property presumption applies to all property on hand at dissolution. Party claiming separate property must prove by clear and convincing evidence.',
  },

  grounds: {
    no_fault: true,
    grounds_options: [
      'Insupportability (no-fault, irreconcilable differences)',
      'Cruelty',
      'Adultery',
      'Conviction of a felony (imprisoned 1+ year, not pardoned)',
      'Abandonment (1+ year)',
      'Living apart (3+ years)',
      'Confinement in mental hospital (3+ years)',
    ],
    statute: 'Texas Family Code §§ 6.001–6.007',
    legal_separation_available: false,
  },

  child_custody: {
    standard: 'best_interest_of_child',
    joint_custody_preference: true,
    factors: [
      'Desires of the child (if 12 or older, child may express preference)',
      'Emotional and physical needs of the child now and in the future',
      'Emotional and physical danger to the child now and in the future',
      'Parental abilities of the individuals seeking custody',
      'Programs available to assist these individuals',
      'Plans for the child by these individuals',
      'Stability of the home or proposed placement',
      'Acts or omissions of the parent indicating the parent-child relationship is improper',
      'Any excuse for acts or omissions of the parent',
    ],
    statute: 'Texas Family Code § 153.002, § 153.134',
    geographic_restrictions: 'Standard: child\'s residence restricted to county of filing and contiguous counties (approx 100-mile radius). Can be modified by agreement or court order.',
  },

  child_support: {
    guideline_type: 'percentage_of_income',
    statute: 'Texas Family Code § 154.125',
    factors: [
      'Net resources of the obligor (gross income minus taxes, SS, health insurance, union dues)',
      'Number of children before the court',
      'Number of other children obligor has duty to support',
      'Percentage guidelines: 1 child=20%, 2=25%, 3=30%, 4=35%, 5=40%, 6+=40%+',
      'Childcare costs',
      'Health insurance costs for children',
    ],
    cap: 'Net resources cap: $9,200/month (as of 2023). Support above cap requires showing child\'s needs.',
  },

  spousal_support: {
    temporary_support_formula: false,
    permanent_support_factors: 'Texas Family Code § 8.052',
    long_term_marriage_years: 10,
    modification_standard: 'Material and substantial change in circumstances',
    termination_events: [
      'Death of either party',
      'Remarriage of supported spouse',
      'Cohabitation in a dating/romantic relationship on a continuing basis',
    ],
    duration_limits: 'Married 10-20 years: max 5 years. Married 20-30 years: max 7 years. Married 30+ years: max 10 years. Disability/family violence: max 10 years or indefinite if disability is permanent.',
  },

  forms: [
    {
      form_number: 'TX-OPD',
      form_name: 'Original Petition for Divorce',
      form_type: 'petition',
      required_when: { always: true },
      order_in_process: 1,
      court_fee: 300.00,
      instructions_url: 'https://www.texaslawhelp.org/toolkit/i-want-divorce',
    },
    {
      form_number: 'TX-CIT',
      form_name: 'Citation (Service of Process)',
      form_type: 'summons',
      required_when: { always: true },
      order_in_process: 2,
      court_fee: 0,
      instructions_url: null,
    },
    {
      form_number: 'TX-WOS',
      form_name: 'Waiver of Service',
      form_type: 'service',
      required_when: { case_type: 'uncontested' },
      order_in_process: 2,
      court_fee: 0,
      instructions_url: null,
    },
    {
      form_number: 'TX-ANS',
      form_name: 'Original Answer',
      form_type: 'response',
      required_when: { case_type: 'contested' },
      order_in_process: 3,
      court_fee: 0,
      instructions_url: null,
    },
    {
      form_number: 'TX-SO',
      form_name: 'Standing Order (Automatic Restraining Order)',
      form_type: 'other',
      required_when: { always: true },
      order_in_process: 1,
      court_fee: 0,
      instructions_url: null,
    },
    {
      form_number: 'TX-IA',
      form_name: 'Sworn Inventory and Appraisement',
      form_type: 'property',
      required_when: { has_property: true },
      order_in_process: 5,
      court_fee: 0,
      instructions_url: null,
    },
    {
      form_number: 'TX-FIS',
      form_name: 'Financial Information Statement',
      form_type: 'financial_disclosure',
      required_when: {
        or: [
          { has_children: true },
          { spousal_support_requested: true },
        ],
      },
      order_in_process: 5,
      court_fee: 0,
      instructions_url: null,
    },
    {
      form_number: 'TX-SPO',
      form_name: 'Standard Possession Order',
      form_type: 'custody',
      required_when: { has_children: true },
      order_in_process: 6,
      court_fee: 0,
      instructions_url: null,
    },
    {
      form_number: 'TX-APP',
      form_name: 'Agreed Parenting Plan',
      form_type: 'custody',
      required_when: { has_children: true },
      order_in_process: 6,
      court_fee: 0,
      instructions_url: null,
    },
    {
      form_number: 'TX-CSO',
      form_name: 'Child Support Order',
      form_type: 'support',
      required_when: { has_children: true },
      order_in_process: 8,
      court_fee: 0,
      instructions_url: null,
    },
    {
      form_number: 'TX-MSD',
      form_name: 'Military Status Declaration',
      form_type: 'declaration',
      required_when: { military_member: true },
      order_in_process: 1,
      court_fee: 0,
      instructions_url: null,
    },
    {
      form_number: 'TX-FDD',
      form_name: 'Final Decree of Divorce',
      form_type: 'judgment',
      required_when: { always: true },
      order_in_process: 10,
      court_fee: 0,
      instructions_url: null,
    },
    {
      form_number: 'TX-ADV',
      form_name: 'Agreed Decree of Divorce (Uncontested)',
      form_type: 'judgment',
      required_when: { case_type: 'uncontested' },
      order_in_process: 10,
      court_fee: 0,
      instructions_url: null,
    },
    {
      form_number: 'TX-VS',
      form_name: 'Bureau of Vital Statistics Form',
      form_type: 'other',
      required_when: { always: true },
      order_in_process: 10,
      court_fee: 0,
      instructions_url: null,
    },
  ],

  counties: [
    {
      county_name: 'Harris',
      court_name: 'Harris County District Courts - Family Law',
      court_address: '201 Caroline St, Houston, TX 77002',
      court_phone: '(713) 274-8700',
      efiling_system: 'eFileTexas',
      efiling_url: 'https://efile.txcourts.gov/',
      filing_fees: { petition: 300, response: 0, motion: 25 },
    },
    {
      county_name: 'Dallas',
      court_name: 'Dallas County Family Courts',
      court_address: '600 Commerce St, Dallas, TX 75202',
      court_phone: '(214) 653-7301',
      efiling_system: 'eFileTexas',
      efiling_url: 'https://efile.txcourts.gov/',
      filing_fees: { petition: 300, response: 0, motion: 25 },
    },
    {
      county_name: 'Bexar',
      court_name: 'Bexar County District Courts - Family Law',
      court_address: '100 Dolorosa, San Antonio, TX 78205',
      court_phone: '(210) 335-2011',
      efiling_system: 'eFileTexas',
      efiling_url: 'https://efile.txcourts.gov/',
      filing_fees: { petition: 300, response: 0, motion: 25 },
    },
    {
      county_name: 'Travis',
      court_name: 'Travis County District Courts - Family Law',
      court_address: '1000 Guadalupe St, Austin, TX 78701',
      court_phone: '(512) 854-9211',
      efiling_system: 'eFileTexas',
      efiling_url: 'https://efile.txcourts.gov/',
      filing_fees: { petition: 300, response: 0, motion: 25 },
    },
  ],
}
